
name: Java

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Build with Maven
      run: |
        mvn clean install
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: deploy-jar
        path: target/*.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check server status
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.TUDRUJ_DDNS_SSH_KEY }}
        script: |
          whoami
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: deploy-jar
        path: .
    - name: Copy build to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.TUDRUJ_DDNS_SSH_KEY }}
        port: ${{ secrets.PORT }}
        source: "*.jar"
        target: "deployment"
    - name: Run service
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.TUDRUJ_DDNS_SSH_KEY }}
        script: |
          cd deployment
          nohup java -jar *.jar &
